# - Информация:

####################################################
#                                                  #
#   LumiaStaffJob | Плагин для администрации!      #
#   Версия: 2.0                                    #
#   Гл. Разработчик: LUMIA | MoonLight Studio.     #
#   Специально для общего доступа                  #
#   Сделано с любовью, спасибо, что выбрали -      #
#   Нас. MoonLight Studio - Исполняет мечты.       #
#   Форум: https://forum.lumiadev.top/index.php    #
#   VK: https://vk.com/moonlightdevelopment        #
#   ТГ: @LumiaDEV                                  #
#                                                  #
####################################################

# - ПРАВА:
# - | В новой версии права вы устанавливаете сами! Какие только захотите префиксы, какие только захотите строки. Больше свободы в плагинах!))
# - | В новой версии доступны плейсхолдеры, какие захотите, думал добавить свои но потом подумал - зачем?)
# - | В новой версии доступны коды, RRGGBB, MiniMessage, HEX, &, § и т.д. Полная свобода
# - | В новой версии доступны звуки, думал добавить эффекты, но подумал - зачем?
# * Но если что - просто стоит попросить. И я без проблем сделаю. Рад идеям.

Settings:
  playSoundMain: true # Если вы вообще не хотите чтобы звуки воспроизводились при старт/енд – то ставьте false | Чтобы не указывать везде что надо/не надо
  cooldownPlugin: 77 # В секундах

# //////////////////// #
#     | ПЕРМИШНЫ       #
# //////////////////// #

Permissions:

  # Если есть что повыше, например Овнер или Девелопер - welcome

  admin:
    permission: lsj.adm
    soundPlay: true
    startJob:
    - ""
    - "&cАдминистратор §7%player_name% начинает работу на сервере!"
    - ""
    endJob:
    - "&7Пожелаем нашему дорогому &cадминистратору &7%player_name% спокойной &cхрючи&7)) До завтра!)"
    - "&7Рабочее время - успешно завершено!"
    soundEnd: ""
    soundStart: "ENTITY_PLAYER_LEVELUP"

  moder:
    permission: lsj.mod
    soundPlay: true
    startJob:
      - ""
      - "&bС добрым утром <gradient:#005AFF:#23D2B0>Модератор</gradient> %player_name%, и сервер. Модератор выходит на работу!"
      - ""
    endJob:
      - "&bДорогому <gradient:#005AFF:#23D2B0>Модератору</gradient> §7%player_name% пора на покой, пожелаем спокойной ночки!"
    soundEnd: ""
    soundStart: "ENTITY_PLAYER_LEVELUP"

    # И так далее, с вашими пермишнами

# //////////////////// #
# | ОБЩИЕ ОБЬЯВЛЕНИЯ   #
# //////////////////// #

Errors:
  errorEnd: "§7Есть что заканчивать? Еще даже не начал :) | /ljob start и вперед!"
  listNull: "§7 - Список сотрудников пуст.. Спят наверное - "
  lenError: "§7Недостаточно аргументов! Использование: /ljob start >3"
  errorStart: "§7По второму кругу хош? | /ljob end тогда уж, зачем начинать если уже работаешь.." # Или ты меня проверяешь? Что, меня хочешь?
  consoleError: "§7Консолька у нас тоже работящая? :3"
  colldownError: "&cПодождите еще %d для продолжения!"
  errorNoPermission: "§7У вас нет прав для выполнения этого действия!"